# Generated by Django 5.0.2 on 2024-02-28 18:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 21, 26, 59, 672061), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='answer',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='answer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 21, 26, 59, 672061), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 21, 26, 59, 672061), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('detail', models.TextField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.quiz')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
