# Generated by Django 5.0.2 on 2024-02-28 18:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_answer_code_answer_created_at_answer_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 21, 33, 21, 445629), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_modified_answers', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 21, 33, 21, 445629), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_modified_questions', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 21, 33, 21, 445629), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_modified_quizes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
    ]
