# Generated by Django 5.0.2 on 2024-03-20 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_rename_quiz_id_result_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 19, 17, 16, 199607), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 19, 17, 16, 199607), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Единственный выбор'), ('multiplie_choice', 'Множественный выбор'), ('ranged', 'Ранжирование')], default='single_choice', max_length=30),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 19, 17, 16, 199607), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(verbose_name='Продолжительность теста в минутах'),
        ),
    ]
